baseURL = "https://www.lacy.page/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Lacy Teakell"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

# Ensure pretty URLs
uglyURLs = true

[params]
  # URL for the avatar on homepage
  avatarURL = "/images/hZL49G.png"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-xl"

  # Description to display on homepage
  description = "Sky above, sand below & peace within"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # Display "back to top" button on posts
  ShowBackToTopButton = true

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = "recent"

  # Footer text
  footer = "YOPA"

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts.html"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1
    
  [[menu.main]]
    name = "Resume"
    pre = ""
    url = "/resume.html"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags.html"
    weight = 3
    
  # [[menu.main]]
  #   identifier = "github"
  #   url = "https://github.com"
  #   weight = 4
    
  #   # We use feather-icons: https://feathericons.com/
  #   pre = "<span data-feather='github'></span>"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false